# Generated by Django 4.1 on 2022-08-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
    ]
