# Generated by Django 4.1 on 2022-08-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_rename_count_book_quantity_rename_name_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='quantity',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
