# Generated by Django 4.1 on 2022-08-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0004_alter_book_isbn_alter_book_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='quantity',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.TextField(),
        ),
    ]
