# Generated by Django 4.1 on 2022-08-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0006_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='rented',
            field=models.IntegerField(default=0),
        ),
    ]
