# Generated by Django 4.1 on 2022-08-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0008_alter_transaction_total_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
